version: "3.8"

services:
  postgres:
    image: iotactile/postgres-custom-16
    environment:
      POSTGRES_DB: vertical_sync_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    shm_size: "256mb"
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - app_network

  prisma-studio:
    image: timothyjmiller/prisma-studio:latest
    ports:
      - "5555:5555"
    environment:
      DATABASE_URL: postgresql://postgres:admin@postgres:5432/vertical_sync_db
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - app_network

  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BASE_URL: ${BASE_URL}
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASSWORD: ${DB_PASSWORD}
        DATABASE_URL: ${DATABASE_URL}
        NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
        CLERK_SECRET_KEY: ${CLERK_SECRET_KEY}
        AWS_BUCKET_NAME: ${AWS_BUCKET_NAME}
        AWS_BUCKET_REGION: ${AWS_BUCKET_REGION}
        AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
        AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    ports:
      - "3001:3000"
    environment:
      - BASE_URL=${BASE_URL}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DATABASE_URL=${DATABASE_URL}
      - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
      - AWS_BUCKET_NAME=${AWS_BUCKET_NAME}
      - AWS_BUCKET_REGION=${AWS_BUCKET_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - app_network

volumes:
  postgres_data:
    name: vertical_sync_postgres_data

networks:
  app_network:
    driver: bridge
